### ISSUE TITLE
Peer Review for Linux

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-jakarta-faces#5]
Review and test this guide by a peer member with the following prespectives
 -  by Firefox
 
 README
 ---
 - [ ] Check the appearance of the guide:
    - [ ] Table of contents
    - [ ] Headings
    - [ ] Paragraphs
    - [ ] code snippets
    - [ ] outputs
    - [ ] links (shoud open a new tab)
    - [ ] hotspots (should highlight the code correctly)
 - [ ] Check that the `pom.xml`, `server.xml`, and java files etc files are clean on the right code pane
    - [ ] lines are not too long and wrapped
    - [ ] lines are aligned nicely
 - [ ] Examples with the right outcomes are provided
 
 `pom.xml`
 ---
 - [ ] Check that the dependencies and plugins are latest in all of the `pom.xml` files:
    - jakarta.jakartaee-api
    - microprofile
    - liberty-maven-plugin
    - etc.
 
 Overall checks:
 ---
 - [ ] Check the consistency of guide with the template and other guides
 - [ ] Check the quality of code according to the best coding practices
 - [ ] Check that the directories are properly structured
 
 Additional tests:
 ---
 - [ ] Test the guide end-to-end with working instruction and sample code with either of the following Java
    - [ ] Java 17
 - [ ] Perform all the defined test cases

**Comment by Ruilin-Ma** [comment]
Ran through the guide on the Ubuntu Linux VM end to end and didn't encounter any issues. All the test criteria mentioned above were successfully satisfied.
